<?php

namespace App\Service\Rag\Quiz\Dto;

/**
 * One question generated by the model, as returned by the platform's
 * structured output for QuizGenerator's system prompt.
 */
final class GeneratedQuestion
{
    /**
     * @param string[] $options
     * @param int[]    $correctIndices
     */
    public function __construct(
        public readonly string $prompt,
        public readonly array $options,
        public readonly array $correctIndices,
        public readonly bool $multiple,
        public readonly string $explanation,
        public readonly string $source,
    ) {
    }

    /**
     * @return array{prompt: string, options: list<string>, correctIndices: list<int>, multiple: bool, explanation: string, source: string}
     */
    public function toArray(): array
    {
        return [
            'prompt' => $this->prompt,
            'options' => array_values($this->options),
            'correctIndices' => array_values($this->correctIndices),
            'multiple' => $this->multiple,
            'explanation' => $this->explanation,
            'source' => $this->source,
        ];
    }
}
